[package]
name = "lafare"
version = "0.1.0"
edition = "2021"

[dependencies]
# https://docs.rs/fltk/latest/fltk/
# "FLTK Rust tutorial" - is a search string to find information on YouTube
fltk = { version = "1.4", features = ["fltk-bundled"] }
# https://docs.rs/rand/latest/rand/
rand = "0.8.5"